- name: install pacemaker, pcs, virsh
  apt: 
    pkg:
    - pacemaker
    - pcs
    - libvirt-clients

- name: Change password to user hacluster
  user:
      name: hacluster
      password: "{{ 'hacluster' | password_hash('sha512') }}"

- name: Copy /etc/hosts
  copy: >
    src=etc/hosts
    dest=/etc/hosts
    mode=644
    owner=root
    group=root


- name: Copy script init_cluster.sh
  copy: >
    src=init_cluster.sh
    dest=/root/init_cluster.sh
    mode=644
    owner=root
    group=root

- name: Create the cluster
  command: sh /root/init_cluster.sh
  when: ansible_hostname == 'nodo1'

- name: Create directory /root/.ssh
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0755'
  register: _create_ssh_key

- name: Generate key rsa
  community.crypto.openssh_keypair:
      path: /root/.ssh/id_rsa
  when: _create_ssh_key['changed']

- name: Copy ssh config
  copy: >
    src=ssh/config
    dest=/root/.ssh/config
    mode=644
    owner=root
    group=root

- name: Display public keys
  command: cat /root/.ssh/id_rsa.pub
  register: command_output

- name: Public keys
  debug:
    msg="{{command_output.stdout}}"
  when: _create_ssh_key['changed']

- name: Pausa
  pause:
    prompt: "Copia las claves públicas de los dos nodos en /root/.ssh/authorizad_keys del host."
  when: _create_ssh_key['changed']

- name: Copy script init_stonith.sh
  copy: >
    src=init_stonith.sh
    dest=/root/init_stonith.sh
    mode=644
    owner=root
    group=root

- name: Configurating stonith
  command: sh /root/init_stonith.sh
  when: ansible_hostname == 'nodo1'
