# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.define :nodo1 do |nodo1|
    nodo1.vm.box = "generic/debian10"
    nodo1.vm.hostname = "nodo1"
    nodo1.vm.network :private_network, ip: "10.1.1.101"
    nodo1.vm.provider "virtualbox" do |v|
      # Create an extra disk of 512 MB (testing purposes)
      unless File.exist?("./disco1.vdi")
        v.customize ["createhd", 
                    '--filename', "./disco1",
                    '--size', 512 ]
        v.customize ['storageattach', :id, 
                    '--storagectl', 'SATA Controller', 
                    '--port', 1, 
                    '--device', 0, 
                    '--type', 'hdd', 
                    '--medium', "./disco1.vdi"]
      end
    end
    nodo1.vm.provider :libvirt do |libvirt|
      unless File.exist?("./disco1.vdi")
        libvirt.storage :file, :size => '512M', :path=> 'disco1.vdi'
      end
    end

  end
  config.vm.define :nodo2 do |nodo2|
    nodo2.vm.box = "generic/debian10"
    nodo2.vm.hostname = "nodo2"
    nodo2.vm.network :private_network, ip: "10.1.1.102"
    nodo2.vm.provider "virtualbox" do |v|
      # Create an extra disk of 512 MB (testing purposes)
      unless File.exist?("./disco2.vdi")
        v.customize ["createhd", 
                    '--filename', "./disco2",
                    '--size', 512 ]
        v.customize ['storageattach', :id, 
                    '--storagectl', 'SATA Controller', 
                    '--port', 1, 
                    '--device', 0, 
                    '--type', 'hdd', 
                    '--medium', "./disco2.vdi"]
      end
    end
    nodo2.vm.provider :libvirt do |libvirt|
      unless File.exist?("./disco2.vdi")
        libvirt.storage :file, :size => '512M', :path=> 'disco2.vdi'
      end
    end

  end
  config.vm.define :dns do |dns|
    dns.vm.box = "generic/debian10"
    dns.vm.hostname = "dns"
    dns.vm.network :private_network, ip: "10.1.1.103"
  end
end
